export const actionTypes = {
	FETCH_USERS_START: 'FETCH_USERS_START',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
	ADD_USER_START: 'ADD_USER_START',
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
	ADD_USER_FAILURE: 'ADD_USER_FAILURE',
	EDIT_USER_START: 'EDIT_USER_START',
	EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
	EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
	REMOVE_USER_START: 'REMOVE_USER_START',
	REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
	REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',
}
